### ISSUE TITLE
Issue with CMake

### ISSUE THREAD

**Issue by edouardoyallon** [facebook/ztorch#1]
Hi,

Thank you for providing this package. I might report a (small) bug that I think I've corrected.

"luarocks make rocks/ztorch-scm-1.rockspec" was leading to an error:

luarocks make rocks/ztorch-scm-1.rockspec
Warning: unmatched variable LUALIB
cmake ... make

-- Found Torch7 in ***/torch/install
CMake Error at ***/torch/install/share/cmake/torch/TorchExports.cmake:16 (ADD_LIBRARY):
  add_library cannot create imported target "TH" because another target with
  the same name already exists.
Call Stack (most recent call first):
  ***/torch/install/share/cmake/torch/TorchConfig.cmake:29 (INCLUDE)
  lib/THZ/CMakeLists.txt:2 (FIND_PACKAGE)

-- Found Torch7 in ***/torch/install
-- Compiling with OpenMP support
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf_lp64: not found
-- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf_lp64: not found
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf_lp64 - mkl_sequential - mkl_core - m]
--   Library mkl_gf_lp64: not found
-- Checking for [mkl_gf - mkl_sequential - mkl_core - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel_lp64 - mkl_sequential - mkl_core - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_sequential - mkl_core - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf_lp64: not found
-- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf_lp64: not found
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl - guide - pthread - m]
--   Library mkl: not found
-- MKL library not found
-- Checking for [openblas]
--   Library openblas: ***/OpenBLAS/libopenblas.so
-- Found a library with BLAS API (open).
-- Found a library with LAPACK API. (open)
-- C inline is supported (inline)
-- Configuring incomplete, errors occurred!

Error: Build error: Failed building.

In ztorch/lib/THZ/CMakeList.txt, I had to comment the second line "FIND_PACKAGE(Torch REQUIRED)" because this instruction is already in the CMakeList.txt of the main folder.

**Comment by colesbury** [comment]
Thanks for reporting this error. I'm having trouble reproducing the issue. What OS are you using? Are you using the default Torch installation?

**Comment by edouardoyallon** [comment]
Thanks for the answer. I report this issue from Ubuntu 12.04. Maybe a package is missing or a global variable that I did not set up? I've been using the standard & updated Torch installation. Thanks again, otherwise I've been safely able to run the software.
